[mongodb]
mongodb.daws86s.bond # these are servers

[mysql]
mysql.daws86s.bond

[redis]
redis.daws86s.bond

[rabbitmq]
rabbitmq.daws86s.bond

[frontend]
172.31.9.175

[cart]
172.31.4.74

[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[local:vars]
#COURSE=Ansible
#DURATION=10HRS
#TRAINER=Sivakumar